config/routes.rb
Test5::Application.routes.draw do

  resources :order_counts


  resources :companies


  resources :search_histories

  # match '/apk', :to => redirect('/weicai_1.1.apk')
  # match '/weicai.apk', :to => redirect('/weicai_1.1.apk')
  
  match '/apk' => 'api::versions#apk'
  match '/weicai.apk' => 'api::versions#apk'
  
  
  resources :ships
  

  resources :payments do
    collection do
      post 'list'
    end
  end


  resources :order_items do
    member do
      get "edit_amount"
      post "save_amount"
    end
  end
  resources :settings


  resources :orders do
    collection do
      get 'print_order'
      get 'auto_make_order'
    end
    member do
      get 'submit'
      get 'continue_buy'
      get 'print_ship'
      get 'loading'
      get 'sign'
      get 'done'
      get 'cancel'
      get 'print'
      get 'reset_cost'
    end
  end


  resources :registrations do
    collection do
      get 'sign_up'
    end
    member do 
      get 'validate_code'
      post 'validate'
      get 'password_new'
      post 'password'
    end
  end
  
  resources :sessions do
    collection do
      delete 'sign_out'
    end
  end
  
  resources :users do
    member do
      get 'active'
      get 'frost'
      post 'recharge'
    end
  end
  resources :prices
  resources :products do
    collection do
      get 'list'
      get 'search'
      get 'export'
      get 'sortable'
      get 'sortable_market'
      get 'sortable_print'
      get 'sortable_series'
      post 'update_sn'
      post "update_market"
      post "update_series"
      get 'print_dm'
      get 'user_buy_list_print'
      get 'inventory'
    end
    member do
      get 'to_up'
      get 'to_down'
      get 'to_file'
      put 'upload_file'
      put 'update_product'
      delete 'delete_attachment'
      get 'change_price'
      get 'change_all_price'
      get 'change_price_cq'
    end
  end
    
    
    
    
    
    
    
    
    
    

  namespace :api, defaults: {format: 'json'} do
    resources :versions do
      collection do
        get 'last_version'
      end
    end
    
    namespace :v1 do
      resources :products do
        collection do
          post 'list'
        end
      end
      resources :users do
        collection do
          post 'sign_up'
          post 'validate'
          post 'sign_in'
        end
      end
      resources :bills
      resources :orders do
        collection do
          post 'list'
        end
      end
      resources :order_items
    end
    
    
    
    
    
    
    
    
    
    namespace :v2 do
      resources :products do
        collection do
          post 'list'
          get 'types'
        end
        member do 
          post 'avatar'
        end
      end
      resources :users do
        collection do
          post 'sign_up'
          post 'get_sign_up_validate_code'
          post 'send_validate_code'
          post 'sign_in'
          get 'has_validate_code'
          post 'update_password'
          post 'change_password'
          post 'update_baidu_user_id'
        end
      end
      resources :bills
      resources :orders do
        collection do
          post 'list'
          post 'auto_make_order'
        end
        member do
          get 'submit'
          get 'continue_buy'
          get 'sign'
          get 'cancel'
        end
      end
      resources :order_items
      resources :payments do
        collection do
          post 'list'
        end
      end
      resources :search_histories do
        collection do
          post 'list'
        end
      end
      
    end


    
  end
  

  
  root :to => 'sessions#new'
end

app/models/user.rb
# encoding: utf-8
class User < ActiveRecord::Base
  attr_accessible :county, :house, :latitude, :longitude, :name, :password, :phone, :street, :string, :towns, :validate_code, :token, :state, :desc, :level, :baidu_user_id, :role, :show_product_img
  
  validates :phone, :presence => true, uniqueness: true
  
  has_many :orders
  has_many :payments, foreign_key: 'payer_id', :order => 'id DESC'

  before_update :change_password
  
  validates :phone, :presence => true
  
  before_create :set_default
  
  state_machine initial: :unvalidate do
    #before_transition :pending => :open, do: :do_done
    event :validate do # 注册
      transition :unvalidate => :unaudited
    end
    event :active do # 审核通过
      transition [:unaudited, :freezed] => :actived
    end
    event :frost do # 冻结
      transition :actived => :freezed
    end
  end
  
  
  def address
    "#{county} #{towns} #{street} #{house}"
  end
  
  def change_password
    if password_changed?
      self.token = generate_token
    end
  end
  
  def admin?
    role=="admin" && ["18628405091", "15810845422"].include?(phone)
  end
  
  def state_
    case self.state
      when "unvalidate" then "注册中"
      when "unaudited" then "待审核"
      when "actived" then "正常"
      when "freezed" then "已冻结"
    end
  end
  
  def overage
    payment = payments.first
    payment.nil? ? 0 : payment.overage
  end
  
  def update_predict
    Predict.update_user self 
  end
  
  private
  def generate_token
    Digest::MD5::hexdigest(id.to_s + password)
  end
  
  def set_default
    self.level = 9
  end
  

end

app/controllers/api/v1/users_controller.rb
# encoding: utf-8
module Api
  module V1
    class UsersController < Api::BaseController
      before_filter :find_user_by_phone, only: [:sign_up, :sign_in, :validate]
      
      # 注册
      def sign_up
        
        unless params[:user][:phone].present?
          return
        end
        @user ||= User.create(phone: params[:user][:phone])
          
        if @user.unvalidate? # 已被注册
          @phone_can_use = true
          
          validate_code = rand(1000..9999)
          code = SMS.send(@user.phone, "注册校验码：#{validate_code}")
          if code > 0
            @user.update_attributes validate_code: validate_code

            @message = "请输入验证码"
            @is_send_validate_code = true
          else
            @is_send_validate_code = false
            @message = "验证码发送失败"
            @@logger ||= Logger.new("#{Rails.root}/log/sms.log")
            @@logger.error SMS::MSG["#{code}"]
          end
        else
          @phone_can_use = false
          @user = nil
          @message = "手机号已被注册"
        end
      end
      
      
      
      
      # 验证校验码
      def validate
        p @user.validate_code
        p params[:user][:validate_code]
        if @user.unvalidate? && @user.validate_code == params[:user][:validate_code]
          @user.validate_code = nil
          @user.state = "unaudited"
          @user.password = password_md5(@user.id, params[:user][:password])
          @user.save
          
          @status = 0 
          @message = "验证成功!" 
        else
          @status = -1
          @message = "验证码错误!" 
        end
      end
      
      
      
      # 登陆
      def sign_in
        @message = "登陆失败！"
        if @user
          p @user.password
          p password_md5(@user.id, params[:user][:password])
          
          if @user.password == password_md5(@user.id, params[:user][:password])
            @current_user = @user
            cookies.permanent[:token] = @user.token
            
            @message = "登陆成功！"
          else
            @user = nil
          end
        end
      end
      
      def show
        @user = User.find(params[:id])
      end
      
      private
      def find_user_by_phone
        @user = User.where(phone: params[:user][:phone]).first
      end

    end
  end
  
end

app/controllers/api/v2/users_controller.rb
# encoding: utf-8
module Api
  module V2
    class UsersController < Api::BaseController
      before_filter :find_user_by_phone, only: [:sign_up, :sign_in, :get_sign_up_validate_code, :send_validate_code, :update_password]
      
      def has_validate_code
        
      end
      
      # 注册
      def sign_up
        if @user
          @message = "手机号已被注册"
          @user = nil
        else
          @user = User.create(phone: params[:user][:phone])
          @user.password = password_md5(@user.id, params[:user][:password])
          @user.state = "unaudited"
          @user.save
          
          Predict.update_user @user
        end
      end
      
      # 验证校验码
      def get_sign_up_validate_code
        unless @user
          @validate_code = params[:validate_code] || rand(1000..9999)
          SMS.send(params[:user][:phone], "#{@validate_code}（微菜验证码）为了保护您的账号安全，验证码短信请勿转发给其他人")
        end
      end
      
      
      # 验证校验码
      def send_validate_code
        if @user
          @validate_code = params[:validate_code] || rand(1000..9999)
          SMS.send(params[:user][:phone], "#{@validate_code}（微菜验证码）为了保护您的账号安全，验证码短信请勿转发给其他人")
          # @validate_code = rand(1000..9999)
          # SMS.send(params[:user][:phone], "注册校验码：#{@validate_code}")
        end
      end
      
      
      # 登陆
      def sign_in
        if @user
          if @user.password == password_md5(@user.id, params[:user][:password])
            @current_user = @user
            cookies.permanent[:token] = @user.token
            @message = "登陆成功！"
          else
            @message = "密码错误！"
            @user = nil
          end
        else
          @message = "手机号未注册！"
        end
      end
      
      def show
        @user = User.find(params[:id])
      end
      
      def update_password
        if @user
          @user.update_attributes password: password_md5(@user.id, params[:user][:password])
        end
      end
      
      def change_password
        @user = User.find(params[:user][:id])
        if @user && @user.password == password_md5(@user.id, params[:user][:old_password])
          @user.update_attributes password: password_md5(@user.id, params[:user][:new_password])
          @message = "修改成功"
          @state = true
        else
          @message = "当前密码错误，修改失败"
          @state = false
        end
      end
      
      def update_baidu_user_id
        @user = User.find(params[:id])
        if @user
          @user.update_attributes baidu_user_id: params[:baidu_user_id] if params[:baidu_user_id].present?
        end
        render nothing: true
      end
      
      
      private
      def find_user_by_phone
        @user = User.where(phone: params[:user][:phone]).first
      end
      

      


    end
  end
  
end

app/controllers/users_controller.rb
# encoding: utf-8
class UsersController < ApplicationController
  load_and_authorize_resource class: 'User'
  
  before_filter :find_user, only: [:show, :edit, :update, :destroy, :active, :frost, :recharge]
  
  def index
    @users = User
    @users = @users.where(state: params[:state]) if params[:state].present?
    @users = @users.where("name LIKE :query OR phone LIKE :query", query: "%#{params[:query]}%") if params[:query].present?
    @users = @users.order("created_at").reverse_order
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(params[:user])
    @user.save
  end

  def update
    @user.update_attributes(params[:user])

    respond_to do |format|
      format.html {redirect_to user_path(@user)}
      format.js { render nothing: true }
    end
    
    
  end

  def destroy
    @user.destroy
    redirect_to users_url
  end
  
  def active
    @user.active
    redirect_to users_url
  end
  
  def frost
    @user.frost
    redirect_to users_url
  end
  
  # 充值
  def recharge
    payment = Recharge.create(params[:payment].merge operator: current_user, payer: @user)
    redirect_to user_path(@user)
  end
  
  private
  def find_user
    if current_user.admin?
      @user = User.find(params[:id])
    else
      @user = current_user
    end
  end
end

app/helpers/users_helper.rb
# encoding: utf-8
module UsersHelper
  
  def phone_no phone
    phone.insert(3, '-').insert(8, '-') if phone.length == 11
  end
end

app/views/users/_form.html.erb
<%= simple_form_for @user, html: {class: 'form-horizontal'} do |f| %>
 	<%= f.input :name, label: '店铺名', input_html: {autocomplete: 'off'} %>
 	<%= f.input :phone, label: '手机号', input_html: {autocomplete: 'off', disabled: 'disabled'}  %>
 	<%= f.input :county, label: '区', input_html: {autocomplete: 'off'}  %>
 	<%= f.input :towns, label: '乡镇', input_html: {autocomplete: 'off'}  %>
 	<%= f.input :street, label: '街道', input_html: {autocomplete: 'off'}  %>
 	<%= f.input :house, label: '小区', input_html: {autocomplete: 'off'}  %>
 	<%= f.input :latitude, label: '经度', input_html: {autocomplete: 'off'}  %>
 	<%= f.input :longitude, label: '纬度', input_html: {autocomplete: 'off'}  %>
 	<%= f.input :level, label: '级别', input_html: {autocomplete: 'off'}  %>
  <%= f.input :desc, label: '备注', input_html: {class: 'span6', rows: 5} %>
	
  <div class="form-actions">
    <%= f.button :submit, '保存', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/_order_tab.html.erb
dingdan

app/views/users/_payment_tab.html.erb
<form method="post" class="simple_form form-horizontal" action="/users/<%= user.id %>/recharge" accept-charset="UTF-8">
	<div class="control-group string optional user_name">
		<label for="user_name" class="string optional control-label">充值金额</label>
		<div class="controls">
			<input type="text" value="" name="payment[amount]" id="user_name" class="string optional" autocomplete="off">
		</div>
	</div>
	
	<div class="control-group text optional user_desc">
		<label for="user_desc" class="text optional control-label">备注</label>
		<div class="controls"><textarea rows="5" name="payment[desc]" id="user_desc" value="" class="text optional span6"></textarea></div>
	</div>
	
	<div class="control-group text optional user_desc">
		<div class="controls"><input type="submit" class="btn" value="充值"></div>
  </div>
</form>

<%= render 'payments/payment' %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="navbar">
  <div class="navbar-inner">
		<form class="navbar-form bs-docs-example form-search">
			<input type="text" name="beginDate" id="beginDate" value="<%= params[:beginDate] %>" dateFormat="yy-mm-dd" > -
			<input type="text" name="endDate" id="endDate" value="<%= params[:endDate] %>" >
			
			<select name="state" style="width: 110px;">
				<option value="">所有状态</option>
				<option value="unaudited" <%= "selected='selected'" if params[:state] == 'unaudited' %>>未审核</option>
				<option value="actived" <%= "selected='selected'" if params[:state] == 'actived' %>>正常</option>
				<option value="freezed" <%= "selected='selected'" if params[:state] == 'freezed' %>>冻结</option>
			</select>
			
	    <input type="text" name="query" class="span2" placeholder="店铺名称" value="<%= params[:query] %>">
	    <button class="btn" type="submit">搜索</button>
		</form>
  </div>
</div>

<table class="table table-striped">
  <tr>
    <th>店铺名</th>
    <th></th>
    <th>手机号</th>
    <th>余额</th>
    <th>验证码</th>
    <th>状态</th>
    <th>级别</th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to user.name, user %></td>
		<td>
			<%= link_to '订购菜单', user_buy_list_print_products_path(user_id: user, type: 'Vegetable', order: 'classify') %>
			<%= link_to '订购习惯', user_buy_list_print_products_path(user_id: user, type: 'Vegetable', admin: true) %>
		</td>
    <td><%= phone_format user.phone %></td>
    <td><%= price_format user.overage %></td>
    <td><%= user.validate_code %></td>
    <td><%= user.state_ %></td>
    <td><%= user.level %></td>
    <td>
			<% if user.unaudited? %>
				<%= link_to '审核通过', active_user_url(user) %> |
			<% elsif user.actived? %>
				<%= link_to '冻结', frost_user_url(user) %> |
			<% elsif user.freezed? %>
				<%= link_to '解冻', active_user_url(user) %> |
			<% end %>
    	<%= link_to '编辑', edit_user_path(user) %> |
    	<%= link_to '删除', user, method: :delete, data: { confirm: '你确定要要删除?' } %>
		</td>
  </tr>
<% end %>
</table>

<br />

<%#= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="pull-right">
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
</div>

<table class="table table-bordered table-condensed">
	<tr>
		<th width=100>店铺名</th>
		<td><%= @user.name %></td>
		<th width=100>注册电话</th>
		<td><%= @user.phone %></td>
	</tr>
	<tr>
		<th>地址</th>
		<td><%= @user.address %></td>
		<th>坐标</th>
		<td><%= "#{@user.latitude}，#{@user.longitude}" if @user.latitude %></td>
	</tr>
	<tr>
		<th>状态</th>
		<td><%= @user.state_ %></td>
		<th>余额</th>
		<td><%= @user.overage %></td>
	</tr>
	<tr>
		<th>备注</th>
		<td colspan=3><%= @user.desc %></td>
	</tr>
</table>


<div style="margin-bottom: 18px;" class="tabbable">
  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#tab1">订单</a></li>
    <li class=""><a data-toggle="tab" href="#tab2">充值</a></li>
  </ul>
  <div style="padding-bottom: 9px; border-bottom: 1px solid #ddd;" class="tab-content">
    <div id="tab1" class="tab-pane active">
			<%= render '/orders/orders_admin', orders: Order.where(user_id: @user).order("id desc"), user: @user %>
    </div>
    <div id="tab2" class="tab-pane">
			<%= render 'payment_tab', user: @user %>
    </div>
  </div>
</div>