config/routes.rb
Test5::Application.routes.draw do

  resources :order_counts


  resources :companies


  resources :search_histories

  # match '/apk', :to => redirect('/weicai_1.1.apk')
  # match '/weicai.apk', :to => redirect('/weicai_1.1.apk')
  
  match '/apk' => 'api::versions#apk'
  match '/weicai.apk' => 'api::versions#apk'
  
  
  resources :ships
  

  resources :payments do
    collection do
      post 'list'
    end
  end


  resources :order_items do
    member do
      get "edit_amount"
      post "save_amount"
    end
  end
  resources :settings


  resources :orders do
    collection do
      get 'print_order'
      get 'auto_make_order'
    end
    member do
      get 'submit'
      get 'continue_buy'
      get 'print_ship'
      get 'loading'
      get 'sign'
      get 'done'
      get 'cancel'
      get 'print'
      get 'reset_cost'
    end
  end


  resources :registrations do
    collection do
      get 'sign_up'
    end
    member do 
      get 'validate_code'
      post 'validate'
      get 'password_new'
      post 'password'
    end
  end
  
  resources :sessions do
    collection do
      delete 'sign_out'
    end
  end
  
  resources :users do
    member do
      get 'active'
      get 'frost'
      post 'recharge'
    end
  end
  resources :prices
  resources :products do
    collection do
      get 'list'
      get 'search'
      get 'export'
      get 'sortable'
      get 'sortable_market'
      get 'sortable_print'
      get 'sortable_series'
      post 'update_sn'
      post "update_market"
      post "update_series"
      get 'print_dm'
      get 'user_buy_list_print'
      get 'inventory'
    end
    member do
      get 'to_up'
      get 'to_down'
      get 'to_file'
      put 'upload_file'
      put 'update_product'
      delete 'delete_attachment'
      get 'change_price'
      get 'change_all_price'
      get 'change_price_cq'
    end
  end
    
    
    
    
    
    
    
    
    
    

  namespace :api, defaults: {format: 'json'} do
    resources :versions do
      collection do
        get 'last_version'
      end
    end
    
    namespace :v1 do
      resources :products do
        collection do
          post 'list'
        end
      end
      resources :users do
        collection do
          post 'sign_up'
          post 'validate'
          post 'sign_in'
        end
      end
      resources :bills
      resources :orders do
        collection do
          post 'list'
        end
      end
      resources :order_items
    end
    
    
    
    
    
    
    
    
    
    namespace :v2 do
      resources :products do
        collection do
          post 'list'
          get 'types'
        end
        member do 
          post 'avatar'
        end
      end
      resources :users do
        collection do
          post 'sign_up'
          post 'get_sign_up_validate_code'
          post 'send_validate_code'
          post 'sign_in'
          get 'has_validate_code'
          post 'update_password'
          post 'change_password'
          post 'update_baidu_user_id'
        end
      end
      resources :bills
      resources :orders do
        collection do
          post 'list'
          post 'auto_make_order'
        end
        member do
          get 'submit'
          get 'continue_buy'
          get 'sign'
          get 'cancel'
        end
      end
      resources :order_items
      resources :payments do
        collection do
          post 'list'
        end
      end
      resources :search_histories do
        collection do
          post 'list'
        end
      end
      
    end


    
  end
  

  
  root :to => 'sessions#new'
end

app/models/search_history.rb
class SearchHistory < ActiveRecord::Base
  belongs_to :user
  attr_accessible :keywords, :user, :user_id, :has_result
end

app/controllers/api/v2/search_histories_controller.rb
module Api
  module V2
    class SearchHistoriesController < Api::BaseController
      def list
        @user = User.find(params[:user][:id])
        if @user
            @search_histories = SearchHistory.where(user_id: @user, has_result: 'true')
        end
  
      end
      
      
    end
  end
end

app/controllers/search_histories_controller.rb
class SearchHistoriesController < ApplicationController
  load_and_authorize_resource class: 'SearchHistory'
  
  # GET /search_histories
  # GET /search_histories.json
  def index
    @search_histories = SearchHistory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @search_histories }
    end
  end

  # GET /search_histories/1
  # GET /search_histories/1.json
  def show
    @search_history = SearchHistory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @search_history }
    end
  end

  # GET /search_histories/new
  # GET /search_histories/new.json
  def new
    @search_history = SearchHistory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @search_history }
    end
  end

  # GET /search_histories/1/edit
  def edit
    @search_history = SearchHistory.find(params[:id])
  end

  # POST /search_histories
  # POST /search_histories.json
  def create
    @search_history = SearchHistory.new(params[:search_history])

    respond_to do |format|
      if @search_history.save
        format.html { redirect_to @search_history, notice: 'Search history was successfully created.' }
        format.json { render json: @search_history, status: :created, location: @search_history }
      else
        format.html { render action: "new" }
        format.json { render json: @search_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /search_histories/1
  # PUT /search_histories/1.json
  def update
    @search_history = SearchHistory.find(params[:id])

    respond_to do |format|
      if @search_history.update_attributes(params[:search_history])
        format.html { redirect_to @search_history, notice: 'Search history was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @search_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /search_histories/1
  # DELETE /search_histories/1.json
  def destroy
    @search_history = SearchHistory.find(params[:id])
    @search_history.destroy

    respond_to do |format|
      format.html { redirect_to search_histories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/search_histories_helper.rb
module SearchHistoriesHelper
end

app/views/search_histories/_form.html.erb
<%= form_for(@search_history) do |f| %>
  <% if @search_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search_history.errors.count, "error") %> prohibited this search_history from being saved:</h2>

      <ul>
      <% @search_history.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :keywords %><br />
    <%= f.text_field :keywords %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/search_histories/edit.html.erb
<h1>Editing search_history</h1>

<%= render 'form' %>

<%= link_to 'Show', @search_history %> |
<%= link_to 'Back', search_histories_path %>

app/views/search_histories/index.html.erb
<h1>Listing search_histories</h1>

<table>
  <tr>
    <th>User</th>
    <th>Keywords</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @search_histories.each do |search_history| %>
  <tr>
    <td><%= search_history.user %></td>
    <td><%= search_history.keywords %></td>
    <td><%= link_to 'Show', search_history %></td>
    <td><%= link_to 'Edit', edit_search_history_path(search_history) %></td>
    <td><%= link_to 'Destroy', search_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Search history', new_search_history_path %>

app/views/search_histories/new.html.erb
<h1>New search_history</h1>

<%= render 'form' %>

<%= link_to 'Back', search_histories_path %>

app/views/search_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @search_history.user %>
</p>

<p>
  <b>Keywords:</b>
  <%= @search_history.keywords %>
</p>


<%= link_to 'Edit', edit_search_history_path(@search_history) %> |
<%= link_to 'Back', search_histories_path %>