config/routes.rb
Test5::Application.routes.draw do

  resources :order_counts


  resources :companies


  resources :search_histories

  # match '/apk', :to => redirect('/weicai_1.1.apk')
  # match '/weicai.apk', :to => redirect('/weicai_1.1.apk')
  
  match '/apk' => 'api::versions#apk'
  match '/weicai.apk' => 'api::versions#apk'
  
  
  resources :ships
  

  resources :payments do
    collection do
      post 'list'
    end
  end


  resources :order_items do
    member do
      get "edit_amount"
      post "save_amount"
    end
  end
  resources :settings


  resources :orders do
    collection do
      get 'print_order'
      get 'auto_make_order'
    end
    member do
      get 'submit'
      get 'continue_buy'
      get 'print_ship'
      get 'loading'
      get 'sign'
      get 'done'
      get 'cancel'
      get 'print'
      get 'reset_cost'
    end
  end


  resources :registrations do
    collection do
      get 'sign_up'
    end
    member do 
      get 'validate_code'
      post 'validate'
      get 'password_new'
      post 'password'
    end
  end
  
  resources :sessions do
    collection do
      delete 'sign_out'
    end
  end
  
  resources :users do
    member do
      get 'active'
      get 'frost'
      post 'recharge'
    end
  end
  resources :prices
  resources :products do
    collection do
      get 'list'
      get 'search'
      get 'export'
      get 'sortable'
      get 'sortable_market'
      get 'sortable_print'
      get 'sortable_series'
      post 'update_sn'
      post "update_market"
      post "update_series"
      get 'print_dm'
      get 'user_buy_list_print'
      get 'inventory'
    end
    member do
      get 'to_up'
      get 'to_down'
      get 'to_file'
      put 'upload_file'
      put 'update_product'
      delete 'delete_attachment'
      get 'change_price'
      get 'change_all_price'
      get 'change_price_cq'
    end
  end
    
    
    
    
    
    
    
    
    
    

  namespace :api, defaults: {format: 'json'} do
    resources :versions do
      collection do
        get 'last_version'
      end
    end
    
    namespace :v1 do
      resources :products do
        collection do
          post 'list'
        end
      end
      resources :users do
        collection do
          post 'sign_up'
          post 'validate'
          post 'sign_in'
        end
      end
      resources :bills
      resources :orders do
        collection do
          post 'list'
        end
      end
      resources :order_items
    end
    
    
    
    
    
    
    
    
    
    namespace :v2 do
      resources :products do
        collection do
          post 'list'
          get 'types'
        end
        member do 
          post 'avatar'
        end
      end
      resources :users do
        collection do
          post 'sign_up'
          post 'get_sign_up_validate_code'
          post 'send_validate_code'
          post 'sign_in'
          get 'has_validate_code'
          post 'update_password'
          post 'change_password'
          post 'update_baidu_user_id'
        end
      end
      resources :bills
      resources :orders do
        collection do
          post 'list'
          post 'auto_make_order'
        end
        member do
          get 'submit'
          get 'continue_buy'
          get 'sign'
          get 'cancel'
        end
      end
      resources :order_items
      resources :payments do
        collection do
          post 'list'
        end
      end
      resources :search_histories do
        collection do
          post 'list'
        end
      end
      
    end


    
  end
  

  
  root :to => 'sessions#new'
end

app/models/bill.rb
# class Bill < ActiveRecord::Base
#   attr_accessible :amount, :operator, :payer
#   
#   belongs_to :payer, class_name: 'User'
#   belongs_to :operator, class_name: 'User'
#   
#   
# end

app/controllers/api/v1/bills_controller.rb
module Api
  module V1
    class BillsController < Api::BaseController
      def index
        @bills = Bills.where()
      end
      
      
    end
  end
end

app/controllers/api/v2/bills_controller.rb
module Api
  module V2
    class BillsController < Api::BaseController
      def index
        @bills = Bills.where()
      end
      
      
    end
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  load_and_authorize_resource class: 'Bill'
  
  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bills }
    end
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
    @bill = Bill.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bill }
    end
  end

  # GET /bills/new
  # GET /bills/new.json
  def new
    @bill = Bill.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bill }
    end
  end

  # GET /bills/1/edit
  def edit
    @bill = Bill.find(params[:id])
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(params[:bill])

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render json: @bill, status: :created, location: @bill }
      else
        format.html { render action: "new" }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bills/1
  # PUT /bills/1.json
  def update
    @bill = Bill.find(params[:id])

    respond_to do |format|
      if @bill.update_attributes(params[:bill])
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill = Bill.find(params[:id])
    @bill.destroy

    respond_to do |format|
      format.html { redirect_to bills_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_form.html.erb
<%= form_for(@bill) do |f| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @bill.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :payer %><br />
    <%= f.text_field :payer %>
  </div>
  <div class="field">
    <%= f.label :operator %><br />
    <%= f.text_field :operator %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bills/edit.html.erb
<h1>Editing bill</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<h1>Listing bills</h1>

<table>
  <tr>
    <th>Payer</th>
    <th>Operator</th>
    <th>Amount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bills.each do |bill| %>
  <tr>
    <td><%= bill.payer %></td>
    <td><%= bill.operator %></td>
    <td><%= bill.amount %></td>
    <td><%= link_to 'Show', bill %></td>
    <td><%= link_to 'Edit', edit_bill_path(bill) %></td>
    <td><%= link_to 'Destroy', bill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bill', new_bill_path %>

app/views/bills/new.html.erb
<h1>New bill</h1>

<%= render 'form' %>

<%= link_to 'Back', bills_path %>

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Payer:</b>
  <%= @bill.payer %>
</p>

<p>
  <b>Operator:</b>
  <%= @bill.operator %>
</p>

<p>
  <b>Amount:</b>
  <%= @bill.amount %>
</p>


<%= link_to 'Edit', edit_bill_path(@bill) %> |
<%= link_to 'Back', bills_path %>