config/routes.rb
Test5::Application.routes.draw do

  resources :order_counts


  resources :companies


  resources :search_histories

  # match '/apk', :to => redirect('/weicai_1.1.apk')
  # match '/weicai.apk', :to => redirect('/weicai_1.1.apk')
  
  match '/apk' => 'api::versions#apk'
  match '/weicai.apk' => 'api::versions#apk'
  
  
  resources :ships
  

  resources :payments do
    collection do
      post 'list'
    end
  end


  resources :order_items do
    member do
      get "edit_amount"
      post "save_amount"
    end
  end
  resources :settings


  resources :orders do
    collection do
      get 'print_order'
      get 'auto_make_order'
    end
    member do
      get 'submit'
      get 'continue_buy'
      get 'print_ship'
      get 'loading'
      get 'sign'
      get 'done'
      get 'cancel'
      get 'print'
      get 'reset_cost'
    end
  end


  resources :registrations do
    collection do
      get 'sign_up'
    end
    member do 
      get 'validate_code'
      post 'validate'
      get 'password_new'
      post 'password'
    end
  end
  
  resources :sessions do
    collection do
      delete 'sign_out'
    end
  end
  
  resources :users do
    member do
      get 'active'
      get 'frost'
      post 'recharge'
    end
  end
  resources :prices
  resources :products do
    collection do
      get 'list'
      get 'search'
      get 'export'
      get 'sortable'
      get 'sortable_market'
      get 'sortable_print'
      get 'sortable_series'
      post 'update_sn'
      post "update_market"
      post "update_series"
      get 'print_dm'
      get 'user_buy_list_print'
      get 'inventory'
    end
    member do
      get 'to_up'
      get 'to_down'
      get 'to_file'
      put 'upload_file'
      put 'update_product'
      delete 'delete_attachment'
      get 'change_price'
      get 'change_all_price'
      get 'change_price_cq'
    end
  end
    
    
    
    
    
    
    
    
    
    

  namespace :api, defaults: {format: 'json'} do
    resources :versions do
      collection do
        get 'last_version'
      end
    end
    
    namespace :v1 do
      resources :products do
        collection do
          post 'list'
        end
      end
      resources :users do
        collection do
          post 'sign_up'
          post 'validate'
          post 'sign_in'
        end
      end
      resources :bills
      resources :orders do
        collection do
          post 'list'
        end
      end
      resources :order_items
    end
    
    
    
    
    
    
    
    
    
    namespace :v2 do
      resources :products do
        collection do
          post 'list'
          get 'types'
        end
        member do 
          post 'avatar'
        end
      end
      resources :users do
        collection do
          post 'sign_up'
          post 'get_sign_up_validate_code'
          post 'send_validate_code'
          post 'sign_in'
          get 'has_validate_code'
          post 'update_password'
          post 'change_password'
          post 'update_baidu_user_id'
        end
      end
      resources :bills
      resources :orders do
        collection do
          post 'list'
          post 'auto_make_order'
        end
        member do
          get 'submit'
          get 'continue_buy'
          get 'sign'
          get 'cancel'
        end
      end
      resources :order_items
      resources :payments do
        collection do
          post 'list'
        end
      end
      resources :search_histories do
        collection do
          post 'list'
        end
      end
      
    end


    
  end
  

  
  root :to => 'sessions#new'
end

app/views/layouts/_header.html.erb
<div class="container">
<div class="row">

<div class="navbar navbar-fixed-top" style="position:absolute;">
  <div class="navbar-inner">
    <div class="container">
			<button data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar" type="button">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
			
      <a class="brand" href="/">微菜</a>
      <div class="container nav-collapse">
				
        
				
				
        <ul class="nav">
          <li class=" <%= 'active' if controller.controller_name == 'products' %>">
						<%= link_to "首页", products_path(type: 'Vegetable')  %>
					</li>
          <!-- <li><%= link_to "水果", products_path(type: 'Fruit')  %></li>
          <li><%= link_to "肉禽蛋", products_path(type: 'Meat')  %></li>
          <li><%= link_to "水产", products_path(type: 'Fish')  %></li>
          <li><%= link_to "粮油", products_path(type: 'Agri')  %></li>
          <li><%= link_to_function "调味品", "javascript:void(0)" %></li>
					-->
						
					
					
          <li class=" <%= 'active' if controller.controller_name == 'orders' %>">
						<a  href="/orders" >订单</a>
					</li>
          <li class=" <%= 'active' if controller.controller_name == 'payments' %>">
						<%= link_to "账单", payments_path %>
					</li>
        </ul>
				
				
        <ul class="nav" style="margin-left: 120px;">
					<% if can? :destroy, Product %>
          <li><%= link_to "商品列表", list_products_path %></li>
					<% end %>
					
					<% if can? :manage, Product %>
          <li><%= link_to "DM单", print_dm_products_path %></li>
					<% end %>
					
					<% if can? :destroy, User %>
          <li><%= link_to "用户", users_path %></li>
					<% end %>
        </ul>
				
				
        <ul class="nav pull-right">
					<% if current_user %>
	          <li><%= link_to current_user.phone, "javascript:void(0)" %></li>
						<li>
							<%= link_to sign_out_sessions_path, method: 'delete', rel: "nofollow", :"data-confirm" => "确定要退出吗？", title: '退出' do %>
								<i class="icon-off"></i>
							<% end %>
						</li>
					<% else %>
	          <li class=" <%= 'active' if controller.controller_name == 'registrations' %>"><%= link_to "注册", sign_up_registrations_path  %></li>
	          <li class=" <%= 'active' if controller.controller_name == 'sessions' %>"><%= link_to "登录", new_session_path  %></li>
					<% end %>
        </ul>
      </div>
    </div>
  </div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "微菜" %></title>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
		<%= render 'layouts/header'%>
    <div class="container">
			
			<div class="row ">
				<div class="span12">
				<% flash.each do |key, value| %>
					<div class="<%= flash_class(key) %>">
						<button type="button" class="close" data-dismiss="alert">&times;</button>
						<%= value %>
					</div>
				<% end %>
				</div>
			</div>
			
      <%#= bootstrap_flash %>
			
      <%= yield %>
      <footer>
        <!-- <p>&copy; Company 2013</p> -->
      </footer>
    </div>
  </body>
</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>百菜网</title>
<meta content="width=device-width; initial-scale=1.0; minimum-scale=1.0; maximum-scale=1.0" name="viewport"/>
<meta content="240" name="MobileOptimized"/>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
	
	<link type="text/css" rel="stylesheet" media="all" href="/assets/application_mobile.css">
</head>
<body>
	<%= render 'layouts/header'%>
	<%= yield %>
</body>
</html>

app/views/layouts/print.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "微菜" %></title>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
		<link href="/assets/order_sn.css" media="all" rel="stylesheet" type="text/css" />
    <%= javascript_include_tag "application" %>
		
		<script type="text/javascript" src="/assets/code128.js"></script>
		<script type="text/javascript" src="/assets/order.js"></script>
		<script type="text/javascript">
		$(function(){
			//= require 
			// window.print();
			// window.close();
		})
		</script>
		
		
  </head>
  <body style="padding-top:0; background-color:#EEEEEE;">
		<!-- max-width:756px; max-height:500px -->
		<!--  -->

				<%= yield %>

		
		
  </body>
</html>

app/views/layouts/products_layout.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "微菜" %></title>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
		
		<script type="text/javascript">
			$(function(){
		
				$("#show_product_img").change(function(){
					if ($("#show_product_img").is(":checked")) { 
						$(".product_img").show();
					}else{
						$(".product_img ").hide();
					}
					$(this).closest('form').submit();
				});
			})
	
	
		</script>
		
  </head>
  <body data-spy="scroll" data-target="#myScrollspy" > 
		<%= render 'layouts/header'%>
		
    <div class="container" >
			
			<div class="row ">
				<div class="span12">
				<% flash.each do |key, value| %>
					<div class="<%= flash_class(key) %>">
						<button type="button" class="close" data-dismiss="alert">&times;</button>
						<%= value %>
					</div>
				<% end %>
				</div>
			</div>
		
			<%= render 'products/search'%>
			
      <%#= bootstrap_flash %>
      <%= yield %>
      <footer>
        <!-- <p>&copy; Company 2013</p> -->
      </footer>
    </div>
  </body>
</html>